spring:
  application:
    name: app
  security:
    user:
      name: admin
      password: changeMe
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:29093

topic-to-send-message: user_audit_topic

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
      base-path: /admin/actuator
  metrics:
    export:
      distribution:
        percentiles-histogram:
          all: true
    tags:
      service: "user-service"
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 8080
  tomcat:
    threads:
      max: 210
      min-spare: 10
resilience4j.ratelimiter:
  instances:
    rateLimiterAPI:
      limitForPeriod: 10
      limitRefreshPeriod: 10s
      timeoutDuration: 0
resilience4j.circuitbreaker:
  instances:
    CircuitBreakerAPI:
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: count_based
      slidingWindowSize: 10