spring:
  application:
    name: app
  security:
    user:
      name: admin
      password: changeMe
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
      base-path: /admin/actuator
server:
  port: 8080
  tomcat:
    threads:
      max: 210
      min-spare: 10