create table file
(
    id       bigint primary key generated by default as identity,
    capacity integer     not null,
    name     varchar(50) not null
);

create table tag
(
    id   bigint primary key generated by default as identity,
    name varchar(50) not null
);

create table file_tag
(
    file_id bigint references file (id) not null,
    tag_id  bigint references tag (id)  not null,
    primary key (file_id, tag_id)
);